version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - ./initdb/sqlsetup00.sql:/docker-entrypoint-initdb.d/sqlsetup00.sql